### ISSUE TITLE
rename library to qConnectBase, appear after installation as lib/site-packages/robotframework-qconnect-base

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/robotframework-qconnect-base#1]
The library shall be renamed to qconnectbase.
It shall appear after installation as lib/site-packages/robotframework-qconnect-base.
Please verify on both, Windows and Linux.

**Comment by test-fullautomation** [comment]
Hi Cuong,
please look into this.
Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
Hi Cuong,
can you give me a short status on this?
The change here requires also adaptations to qconnect-dlt, correct?
Thank you,
 Thomas

**Comment by milanac030988** [comment]
Hello Thomas,
I found that you have changed the package name to QConnectBase in the latest revision.  After installing the package name will be QConnectBase. I have a little bit confused that if your desired name should be QConnectBase or robotframework-qconnect-base? Please help me confirm.
The change of QConnectBase library name will not effect to the qconnect-dlt if the qconnect-dlt not change the package name.
Thank you,
Cuong

**Comment by test-fullautomation** [comment]
Hi Cuong,
uups. I'm also a bit confused now.
The package shall be called robotframework-qconnect-base and robotframework-qconnect-dlt.
I changed the base folder from QConnectLibrary to QConnectBase,. If this has no impact to the function of robotframework-qconnect-dlt, then it's perfect. I did not test this.
Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
this issue is solved.
