### ISSUE TITLE
Example in README files is not up-to-date

### ISSUE THREAD

**Issue by ngoan1608** [test-fullautomation/robotframework-qconnect-base#42]
Hi Cuong,

The example in README file is not updated, the old library name `QConnectionLibrary` is still used.

Thank you,
Ngoan

**Comment by test-fullautomation** [comment]
Hi @milanac030988 ,
please fix this with high priority.
Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
Hi  @milanac030988 ,
what is the status of this issue?
Thank you,
 Thomas

**Comment by milanac030988** [comment]
Hello @test-fullautomation, 

Fixed by Fixed in [-Update Readme by milanac030988 · Pull Request #44 · test-fullautomation/robotframework-qconnect-base](https://github.com/test-fullautomation/robotframework-qconnect-base/pull/44)

Thank you,
Cuong
